spring:
  main:
      allow-bean-definition-overriding: true
  application:
    name: orders-kafka-streams
  profiles:
    active: local # this activates the profile
server.port : 8080
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    consumer:
      auto-offset-reset: latest
    streams:
      bootstrap-servers: localhost:9092
      application-id: orders-kafka-streams5
    properties:
      default:
        key:
          serde: 'org.apache.kafka.common.serialization.Serdes$StringSerde'
        value:
          serde: 'org.apache.kafka.common.serialization.Serdes$StringSerde'
        deserialization:
          exception:
            handler: 'org.apache.kafka.streams.errors.LogAndContinueExceptionHandler'
        serialization:
          exception:
            handler: 'com.learnkafkastreams.exceptionhandler.StreamsSerializationExceptionHandler'