spring:
  application:
    name: greeting-kafka-streams
#  main:
#      allow-bean-definition-overriding: true
  profiles:
    active: local # this activates the profile
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    streams:
      bootstrap-servers: localhost:9092
      application-id: greeting-streams-springboot
    properties:
      default:
        key:
          serde: 'org.apache.kafka.common.serialization.Serdes$StringSerde'
        value:
          serde: 'org.apache.kafka.common.serialization.Serdes$StringSerde'
        deserialization:
          exception:
#            handler: 'org.apache.kafka.streams.errors.LogAndContinueExceptionHandler'
#            handler: 'com.learnkafkastreams.exceptionhandler.StreamsDeserializationErrorHandler'
        production:
          exception:
            handler: 'com.learnkafkastreams.exceptionhandler.StreamsSerializationExceptionHandler'

